version: '2'

services:
  web:
    build: .
    ports:
      - 3000:3000
      - 3838:3838
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db

volumes:
  dbdata: